### ISSUE TITLE
Rename all component to use slides-prefix and reconfigure angular-cli

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#1]
something which is not `app` but not as long as presentation?

**Comment by aziz512** [comment]
@kirjs `slides` ?

**Comment by matheo** [comment]
npm install `ng-slides`?

**Comment by kirjs** [comment]
I like slides

**Comment by tessaSAC** [comment]
Do you mean like [this](https://github.com/AngularNYC/angular-presentation/pull/137)?

What is the difference between prepending with `slides-` and putting all the relevant components in a `slides` folder?

**Comment by kirjs** [comment]
Basically right now all components have `app-` prefix. 
app-presentation, app-slide, etc. 
The ideas is to change it to `slides-`
slides-presentation, slides-editor, etc. 

I actually have no idea what to do with slide. `slides-slide`?

**Comment by tessaSAC** [comment]
Oh lol I thought it was regarding file names for the demo part. Whoops! `slide+`?

**Comment by tessaSAC** [comment]
So something like [this](https://github.com/AngularNYC/angular-presentation/pull/137)?

I did a find and replace all on `app-` with `slides-` and edited the cli config file. I tested it on a new component and the selector started with `slides-` instead of `app-`
