### ISSUE TITLE
Find a way to indicate if the code example is editable

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#107]

**Comment by tessaSAC** [comment]
what if the code editor had a color theme applied and editable code has a matching theme?

**Comment by kirjs** [comment]
Ended up doing it this way:
![2jjnvve1u3a](https://cloud.githubusercontent.com/assets/2545357/25778019/df82e834-32bf-11e7-981c-08e8afff79bb.png)
