### ISSUE TITLE
Make file names in the tests link directly to the files.

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#108]
![jzvsc29j0ez](https://cloud.githubusercontent.com/assets/2545357/25619822/3f3fe492-2f1a-11e7-9d39-42dd9a176f84.png)

**Comment by kirjs** [comment]
Hey Daniel, seems like you're in that area of the app, alternatively I could take a look when your tree PR is in.

**Comment by foozebox** [comment]
@kirjs  Sure thing, taking a look now.

**Comment by kirjs** [comment]
Thanks Daniel!
