### ISSUE TITLE
Navigating back and forth breaks the preview

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#132]
Find two consequent slides with playgrounds
go to slide 1
go to slide 2
go back to slide 1
Slide 1 is missing preview.

**Comment by tessaSAC** [comment]
Tried to locate this bug but actually just had trouble navigating/going back in general. It seems like every time I came across a "whole" picture slide the likelihood of getting stuck there was very high; is it just on my computer?
<img width="1272" alt="screen shot 2017-05-07 at 10 10 51 pm" src="https://cloud.githubusercontent.com/assets/20037396/25787769/41bf0a2a-3372-11e7-8867-1d373ac9660d.png">
☝️uri changes but cannot navigate in either direction. Also not much to see here; did it load properly?

**Comment by kirjs** [comment]
I actually fixed this bug, and the fix broke previews. 
Looking into that now.

**Comment by tessaSAC** [comment]
ooh, 👁 🌊

**Comment by kirjs** [comment]
Should be fixed in #167
