### ISSUE TITLE
Add a "hint" slide explaining how to use Array.prototype.filter

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#143]
It's used in a couple of exercise and a lot of people are not familiar with the syntax

**Comment by RingoKam** [comment]
Where do you want the hint?

**Comment by kirjs** [comment]
Actually not sure, ideally I would have it hidden, and then a test would have a link to it

**Comment by kirjs** [comment]
But I'd say for now let's just have it before the first exercise

**Comment by RingoKam** [comment]
Hmm how about as a tool tip on the word "filter"?

**Comment by kirjs** [comment]
Just added a slide for now
