### ISSUE TITLE
When running app in safari browser, if you add feedback, it clears the code you have typed and also does not submit feedback properly

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#144]

**Comment by tessaSAC** [comment]
Buttons no longer seem to work at all on master branch. Wondering if [this](http://stackoverflow.com/questions/36845515/mouseevent-path-equivalent-in-firefox-safari) is why

(Seems to be triggering menu opening based on ` const belongsToPopup = event['path']`)
