### ISSUE TITLE
Fix up the browser window component to scale appropriately

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#17]

**Comment by kirjs** [comment]
![g8vip7nl0d3](https://cloud.githubusercontent.com/assets/2545357/25566276/b16768e2-2da3-11e7-8235-8dd5348bc11d.png)
Right now browser top is an image and it does not scale horizontally

**Comment by tessaSAC** [comment]
related to #149

**Comment by kirjs** [comment]
Fixed thanks to @joeycatxx!!!
