### ISSUE TITLE
Monaco - make validation less aggressive

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#170]
Feedback: the linting is a little overzealous. it looks like there's an error when I simply haven't finished typing the line.

**Comment by tessaSAC** [comment]
I tried researching this for several hours last weekend but couldn't find anything regarding the linter settings in the files or online?

**Comment by kirjs** [comment]
Monaco isn't documented super well unfortunately, I wouldn't expect there to be a simple switch for it

**Comment by kirjs** [comment]
Closing this as a super low priority
