### ISSUE TITLE
Make sure that everything works well for the 1920x1200

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#173]
Looks like this is the one it's actually going to be used for.

**Comment by tessaSAC** [comment]
To add onto this:
@willangley: (Classes - Access modifiers)
This slide doesn't fit on my MacBook's screen, and there's little indication I need to scroll it.

When navigating with arrow keys sometimes causes it to position slide from bottom up 😰
<img width="1280" alt="screen shot 2017-05-12 at 3 35 57 pm" src="https://cloud.githubusercontent.com/assets/20037396/26014039/f4ded518-3728-11e7-9033-8fb9942da96a.png">

**Comment by tessaSAC** [comment]
Also seemingly(??? still haven't been able to nail this down and don't know the cause) based on the size of the window when the index is loaded subsequent or previous slides are sized funny and/or have weird features like this one I just discovered (background is scrollable)
<img width="599" alt="screen shot 2017-05-12 at 8 27 45 pm" src="https://cloud.githubusercontent.com/assets/20037396/26020846/dd6f6b76-3751-11e7-9738-affe0a412dee.png">
