### ISSUE TITLE
Find a good way to track progress for the feedback

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#190]

**Comment by MichaelSolati** [comment]
Not sure if this'll help....

(https://developer.github.com/v3/issues/#create-an-issue)[https://developer.github.com/v3/issues/#create-an-issue]

**Comment by tessaSAC** [comment]
Now that @aziz512 made the GitHub integration, can we use GitHub Projects to track it? Or do you mean on `feedback-page` too?

**Comment by kirjs** [comment]
Amazing job @aziz512
