### ISSUE TITLE
The layout of this page doesn't let me use my whole screen.

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#239]
The layout of this page doesn't let me use my whole screen. 
Author: Stephen Fluin
Slide: [Local](http://localhost:4200/typescript/exercise),  [Public](https://angular-presentation.firebaseapp.com/typescript/exercise)

**Comment by kirjs** [comment]
Exercises don't have to be limited by slide size.

**Comment by tessaSAC** [comment]
related to #173?

**Comment by kirjs** [comment]
I'd say close for now
