### ISSUE TITLE
The "Get rid of FAKE_VIDEOS" test doesn't seem to work, it won't clear after I remove the FAKE_VIDEOS array and any use of the variable on the "app.co

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#247]
The "Get rid of FAKE_VIDEOS" test doesn't seem to work, it won't clear after I remove the FAKE_VIDEOS array and any use of the variable on the "app.component.ts" file 
Author: Sean
Slide: [Local](http://localhost:4200/dependency-injection/exercise),  [Public](https://angular-presentation.firebaseapp.com/dependency-injection/exercise)

Another comment from Maria:
I'm also having the same issues as Sean. I tried everything that should have gotten rid of the FAKE_VIDEOS, and they didn't go away. Also, regarding injecting the VideoService, I tried from the examples to replicate here, and it didn't work. This section should delve deeper as well. it is very confusing.

**Comment by kirjs** [comment]
@sean-r-martin Is this still the case? I tried deleting the array and it seems to work

**Comment by sean-r-martin** [comment]
I'm not sure why it wasn't working for me before, but I also tried it and it's working for me now.
