### ISSUE TITLE
should we specify that the class shouldn't be a default export (doesn't pass tests) or is that implicit?

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#274]
should we specify that the class shouldn't be a default export (doesn't pass tests) or is that implicit?
Author: tessaSAC
Slide: [Local](http://localhost:4200/typescript/exercise),[Public](https://angular-presentation.firebaseapp.com/typescript/exercise)

**Comment by kirjs** [comment]
@tessaSAC Since we never mention `export default` I'd say it's a low priority, but would be nice to show an error message

**Comment by tessaSAC** [comment]
Would it be incorrect or just not what we're expecting?

**Comment by kirjs** [comment]
We could use it as a safe net for people who would know about it and want to use it for some reason, we can have a human readable message saying it won't work. 

I think default exports are generally discouraged, at least in the angular world.

**Comment by tessaSAC** [comment]
So it could work but not best practice?

**Comment by kirjs** [comment]
Considering closing this one, as the benefits seem to be disproportional to the amount of work needed
