### ISSUE TITLE
Does the let here describe es6 let or its just string "let"

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#311]
Does the let here describe es6 let or its just string "let"
Author: Mohammad Khan
Slide: [Local](http://localhost:4200/templates/conditional-display-ngfor),[Public](https://angular-presentation.firebaseapp.com/templates/conditional-display-ngfor)

**Comment by kirjs** [comment]
would be nice to have more context, though low priority

**Comment by tessaSAC** [comment]
related to #405

**Comment by kirjs** [comment]
merged
