### ISSUE TITLE
circleColor isn't used on <app-circle>, in the BoxComponent's template

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#312]
circleColor isn't used on <app-circle>, in the BoxComponent's template
Author: Daniel Taveras
Slide: [Local](http://localhost:4200/component-tree/parent-child-component),[Public](https://angular-presentation.firebaseapp.com/component-tree/parent-child-component)

**Comment by kirjs** [comment]
solution here is to get rid of the `circleColor` property.

**Comment by tessaSAC** [comment]
probably related to #313
