### ISSUE TITLE
For the first point, it is kind of confusing. I will filter FAKE_VIDEOS and return the value if res.title == searchString, but it seems like it would 

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#348]
For the first point, it is kind of confusing. I will filter FAKE_VIDEOS and return the value if res.title == searchString, but it seems like it would not pass.
Author: Thomas Chen
Slide: [Local](http://localhost:4200/templates/exercise-3),[Public](https://angular-presentation.firebaseapp.com/templates/exercise-3)

**Comment by tessaSAC** [comment]
Can we close one of the two or do you think they have different questions?
