### ISSUE TITLE
Step #1 needs more clarity

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#355]
Step #1 needs more clarity
Author: Shahruk
Slide: [Local](http://localhost:4200/templates/exercise-3),[Public](https://angular-presentation.firebaseapp.com/templates/exercise-3)

**Comment by kirjs** [comment]
Agree, not worded well

**Comment by tessaSAC** [comment]
related to #356, #348

**Comment by kirjs** [comment]
I don't think "don't use exact match" is helpful (makes me think `==` vs `===`). Can we just take it out?
Author: tessaSAC
Slide: [Local](http://localhost:4200/templates/exercise-3),[Public](https://angular-presentation.firebaseapp.com/templates/exercise-3)

**Comment by kirjs** [comment]
For the first point, it is kind of confusing. I will filter FAKE_VIDEOS and return the value if res.title == searchString, but it seems like it would not pass.
Author: Thomas Chen
Slide: [Local](http://localhost:4200/templates/exercise-3),[Public](https://angular-presentation.firebaseapp.com/templates/exercise-3)
