### ISSUE TITLE
another 'any' type property?

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#381]
another 'any' type property?
Author: tessaSAC
Slide: [Local](http://localhost:4200/component-tree/exercise-1),[Public](https://angular-presentation.firebaseapp.com/component-tree/exercise-1)

**Comment by kirjs** [comment]
@tessaSAC Not sure I understand this one?

**Comment by tessaSAC** [comment]
I think because the video Array is type `any` I was wondering if we should change this.

**Comment by tessaSAC** [comment]
Not sure what I was writing about. Maybe I put it on the wrong slide by accident or was thinking the interface thing could be explained more
