### ISSUE TITLE
So far this whole section is making no sense to me because it is only grazed over. There is a lot of information here but it is not delved into deeply

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#386]
So far this whole section is making no sense to me because it is only grazed over. There is a lot of information here but it is not delved into deeply enough.
Author: Maria Campbell
Slide: [Local](http://localhost:4200/dependency-injection/consume-injectable),[Public](https://angular-presentation.firebaseapp.com/dependency-injection/consume-injectable)

**Comment by kirjs** [comment]
Before 3 steps need to explain better what exactly we're trying to do.

**Comment by tessaSAC** [comment]
related to #384

**Comment by kirjs** [comment]
Argeed
