### ISSUE TITLE
Someone wants the navigation bar explained

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#395]
Comment for the whole sequence, not specific to this page: The orange navigation bar at the top could be larger/more visible or have a word of explanation at the beginning. Didn't notice it was interactive until almost through the tutorial.
Author: Angelo
Slide: [Local](http://localhost:4200/create-first-app/exercise-bootstrap-pre),[Public](https://angular-presentation.firebaseapp.com/create-first-app/exercise-bootstrap-pre)

**Comment by kirjs** [comment]
Argeed

**Comment by DanBotero** [comment]
Something like this? 
<img width="1440" alt="screen shot 2017-05-14 at 2 40 03 pm" src="https://cloud.githubusercontent.com/assets/18050806/26036824/7ff77ea8-38b3-11e7-969c-16d4039bb08f.png">

please let me know if the grammar is good or what would be a better message. 
This would happen in only on the intro slides by using intro.js

**Comment by kirjs** [comment]
Looks good. 
I'd do it as a "by the way..." in the mini exercise.

**Comment by DanBotero** [comment]
Something like this? ....
"By the way...the progress bar can help you navigate through this section. 'Red' blocks are exercises ;)"

**Comment by kirjs** [comment]
Sure, actually do it in the exercise then. Since mini exercise is not red and users haven't seen exercises yet.

**Comment by DanBotero** [comment]
But we should explain the progress bar in the intro no? I mean, that way user knows that is there...
"...Didn't notice it was interactive until almost through the tutorial..."

**Comment by kirjs** [comment]
there are 3 milestones after that, and I don't think there's real need in the progress bar before the actual exercise. 
(Also I don't think it's than useful without showing previews or at least headers)

**Comment by DanBotero** [comment]
<img width="1440" alt="screen shot 2017-05-14 at 4 24 58 pm" src="https://cloud.githubusercontent.com/assets/18050806/26037496/ded37266-38c1-11e7-83f2-c8395f832534.png">
Done.
