### ISSUE TITLE
Can add default object/values for NgModule/component in code completion 

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#416]
Can add default object/values for NgModule/component in code completion 
Author: Santosh
Slide: [Local](http://localhost:4200/create-first-app/overview),[Public](https://angular-presentation.firebaseapp.com/create-first-app/overview)

**Comment by kirjs** [comment]
don't understand

**Comment by DanBotero** [comment]
Is he trying to say that there is an option to add defaults to the NgModule arrays?
ex: 
@NgModule({
  imports: [ BrowserModule (Default via completion) ],
  declarations: [ HelloWorldComponent (Default via completion)],
  bootstrap: [ HelloWorldComponent (Default via completion)],
})

Something like this... https://www.npmjs.com/package/ng2-auto-complete
???

**Comment by kirjs** [comment]
hard to say

**Comment by kirjs** [comment]
closing, can't understand
