### ISSUE TITLE
Hide only showing intro only once behind a flag or disable for now

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#425]
cc @tessaSAC

**Comment by kirjs** [comment]
Just realized there will be multiple people using this from the same station, so can't really using local storage for the event

**Comment by tessaSAC** [comment]
thought as much... almost the big day! I don't think the intro thing is in master though. did you want me to take out the check for the tour?

**Comment by NothingEverHappens** [comment]
Yes please! Or comment out as we'll need it eventually

**Comment by tessaSAC** [comment]
What is a flag?

**Comment by NothingEverHappens** [comment]
Basically a queryParameter, similar to this: 
https://github.com/AngularNYC/angular-presentation/blob/tourError/src/app/presentation/presentation/presentation.component.ts#L44

We could something like "showIntroOnce" or something. 

I think it would be cheaper just to comment it out for now.

**Comment by tessaSAC** [comment]
ooh, I see
