### ISSUE TITLE
Assert there are no slides with the same ID 

### ISSUE THREAD

**Issue by DanBotero** [AngularNYC/angular-presentation#43]

**Comment by kirjs** [comment]
Intellij does that

**Comment by prestonvanloon** [comment]
I think @DanBotero intended this to be a unit test of some kind. Not everyone uses Intellij. 

Reopening, but feel free to close if this isn't a priority.

**Comment by kirjs** [comment]
Ok, good call, assertion won't harm

**Comment by DanBotero** [comment]
Done.
