### ISSUE TITLE
Display the slide feedback in the slides

### ISSUE THREAD

**Issue by DanBotero** [AngularNYC/angular-presentation#44]

**Comment by foozebox** [comment]
@DanBotero Could you please elaborate on this a bit?

**Comment by kirjs** [comment]
We have a feedback widget which allows the user to send us feedback. 
Right now messages are saved, but there's no good way to retrieve it. 

The task is to fetch a list of messages for from FireBase and display below the form. 
Only messages filed for the specific slide should be displayed.
![image](https://cloud.githubusercontent.com/assets/2545357/25539601/f6dda434-2c15-11e7-8e33-77d68a23d87e.png)

**Comment by tessaSAC** [comment]
fixed
