### ISSUE TITLE
Someone may not figure out that to call the `search` function in the constructor they need to call it using `this`(this.search("") instead of just sea

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#445]
Someone may not figure out that to call the `search` function in the constructor they need to call it using `this`(this.search("") instead of just search(""))
Author: Emmanuel Geanrd
Slide: [Local](http://localhost:4200/templates/exercise-3),[Public](https://angular-presentation.firebaseapp.com/templates/exercise-3)

**Comment by kirjs** [comment]
Prob a duplicate of something else

**Comment by tessaSAC** [comment]
similar to #379?

**Comment by kirjs** [comment]
hahaha, they found each other
