### ISSUE TITLE
Remove or warn against "any" in tutorials

### ISSUE THREAD

**Issue by LOZORD** [AngularNYC/angular-presentation#61]
I could see there being an argument for easing the transition, but I believe that [`any`](https://github.com/kirjs/angular-presentation/blob/bdb8ea1879e45cc5a7e7681438ccf8ebd0416e32/src/app/demo/typescript/typescript.component.ts#L20) should be warned against for people learning TS. It might encourage bad habits with typing.

**Comment by kirjs** [comment]
I believe we have pretty strict settings in monaco, and any is not allowed
