### ISSUE TITLE
Add section about "ng*=" attributes in Templates lesson

### ISSUE THREAD

**Issue by LOZORD** [AngularNYC/angular-presentation#66]
Basically as an alternative to something like `<img src="{{foo}}">`, we can introduce the `<img ngSrc="foo">`.

**Comment by tessaSAC** [comment]
As in making like a custom directive or something?

**Comment by kirjs** [comment]
I'm actually not sure, is it kinda like 
<img [src]="foo"> ?

**Comment by tessaSAC** [comment]
Yeah personally I couldn't find `ngSrc` in the docs, only the binding way.

**Comment by LOZORD** [comment]
Hmm, I might have been thinking of something from Angular 1 😖 

Maybe include something saying that `[src]="link"` and `src="{{link}}"` are (somewhat) equivalent?

Otherwise, feel free to close.

**Comment by kirjs** [comment]
haha, no worries, thanks! we should have that slide somewhere

**Comment by tessaSAC** [comment]
That makes sense. I'm kinda glad they switched it to this style, feels more consistent 🙂
