### ISSUE TITLE
Find a nicer workflow for exercises completion

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#72]
Currently we have this. 
Maybe add a nice button?
![njgcg9gir0m](https://cloud.githubusercontent.com/assets/2545357/25557849/69ce2306-2ce8-11e7-9db7-628d3a2f0190.png)

**Comment by tessaSAC** [comment]
From #236:

Hard to tell what I should do when it's all green.
I know that it says "Go to the next slide" but that's hard to notice.
Author: John Paul

**Comment by kirjs** [comment]
<img width="1253" alt="screen shot 2017-05-17 at 10 57 39 pm" src="https://cloud.githubusercontent.com/assets/2545357/26188490/513e1b1e-3b54-11e7-8e5e-49dd5a91c445.png">
I'd say it's solved
