### ISSUE TITLE
Create a small set of slides on how to start with VS code quickly

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#73]
* How to install
* All necessary plugins (editor config? css-formatter? anything else?)
* All required shortcuts (how to format, how open file, how to search globally, etc)

**Comment by AryanJ-NYC** [comment]
In relation to Angular or just VScode?

**Comment by kirjs** [comment]
Basically we have a lot of people coming who use sublime and lose in productivity because of that. 
They are also reluctant to move to VSCode, because they'd have to learn it from scratch. 

The idea behind this task is to create a guide for them to start with VSCode quickly, including most of the thing they'll need to figure out to work on this particular project.

**Comment by tessaSAC** [comment]
Haha like meeee

If it helps, what extensions I installed for VSC so far are:
-tslint
-eslint
-auto close tag
-auto rename tag
-autofilename
-beautify (I'm unsure if this replaces the need for the css package we found)
-SublimeText Keymap

I installed others too (snippets, themes, git stuff, etc) but these seem the most relevant to my VSC experience angular-wise. Love to hear if I'm missing any good ones!
