### ISSUE TITLE
Create "Pipes" Milestone

### ISSUE THREAD

**Issue by kirjs** [AngularNYC/angular-presentation#77]
https://docs.google.com/presentation/d/1Wh4ZwTKG1h66f3mTD4GQO8rKwGDEJeBSvUDJ3udU1LA/edit#slide=id.g1b20e4e474_0_42

**Comment by DanBotero** [comment]
Is anyone working on this?

**Comment by kirjs** [comment]
All yours!

**Comment by DanBotero** [comment]
Perfect!!
