### ISSUE TITLE
Menu shortcut is causing a full page reload

### ISSUE THREAD

**Issue by prestonvanloon** [AngularNYC/angular-presentation#86]
In `angular-presentation/src/app/presentation/menu-shortcut/menu-shortcut.component.html`
```
<p><a [href]="route.path + '/0'">{{route.name}}</a></p>
```

This causes a full page reload rather than a route change.

**Comment by kirjs** [comment]
I'm in that area

**Comment by kirjs** [comment]
Daniel fixed this
